// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCecGukw-9fkcXnE5n0PLzZchJ6U41P5I',
    appId: '1:305207723729:web:6e9156dda6442ee2fd27f0',
    messagingSenderId: '305207723729',
    projectId: 'learnascent-lms',
    authDomain: 'learnascent-lms.firebaseapp.com',
    storageBucket: 'learnascent-lms.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfyBGLKIzvNWO8FCI4V8qAkxmuDH8ngho',
    appId: '1:305207723729:android:ebc83c968a62d30cfd27f0',
    messagingSenderId: '305207723729',
    projectId: 'learnascent-lms',
    storageBucket: 'learnascent-lms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGAip_KN0Ffjy6j2iIAQomfUNSdRxnkf0',
    appId: '1:305207723729:ios:3a3302d8e71cca89fd27f0',
    messagingSenderId: '305207723729',
    projectId: 'learnascent-lms',
    storageBucket: 'learnascent-lms.appspot.com',
    iosClientId: '305207723729-tqfs1kqbe1c7n5dq4rdcs1l8l1rfjdrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnascentLms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGAip_KN0Ffjy6j2iIAQomfUNSdRxnkf0',
    appId: '1:305207723729:ios:370e57cf0347afb6fd27f0',
    messagingSenderId: '305207723729',
    projectId: 'learnascent-lms',
    storageBucket: 'learnascent-lms.appspot.com',
    iosClientId: '305207723729-ibs5238arksv19v01e571t8aoic5efaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnascentLms.RunnerTests',
  );
}
